### ISSUE TITLE
Roadmap planning for MEAN.JS 0.5.0

### ISSUE THREAD

**Issue by lirantal** [meanjs/mean#657]
Features
- ~~0.4.0 - refactor_user #559 (need PR work)~~ added to backlog (mleanos)
- ~~JWT (JSON Web Tokens) authentication method (#1163)~~ added to backlog (mleanos)
- [x] Deprecating Grunt in favor of Gulp (#1175)
- [x] Angular 1.4
- [x] Angular Styleguide - https://github.com/johnpapa/angular-styleguide
  - [X] Articles
  - [x] Core (#1202)
  - [x] Users (#1208)
- [x] #807 [Enhancement] Articles admin @ilanbiala

General Cleanups
- [x] Cleaning up the /client issue #608 ( @trainerbill )

Documentation
- ~~Support deploying MEANJS to Cloud Foundry #681~~ support dropped & feature removed with https://github.com/meanjs/mean/pull/1476 (mleanos)

**Comment by simison** [comment]
https://github.com/johnpapa/angular-styleguide

**Comment by lukekhamilton** [comment]
+1

**Comment by simison** [comment]
Supposing 0.5.0 won't hit the master branch very soon, we could try to include new ng-router. https://github.com/meanjs/mean/issues/530 once its ready/documented.

Using Angular 1.5 would be a good step towards 2.0 some time in the future (0.6.0?)

**Comment by fatty1380** [comment]
> https://github.com/johnpapa/angular-styleguide #490

THIS!!!! Some key highlights that I've adopted in my project:
* "$scope must die!" -  use `controller as` in place of `$scope` [Y030:View Syntax](https://github.com/johnpapa/angular-styleguide#style-y030), [Y031:Controller Syntax](https://github.com/johnpapa/angular-styleguide#style-y031) and [Y032:with vm](https://github.com/johnpapa/angular-styleguide#style-y032]
* IIFE : Immediately Invoked Function Expressions [Style Y010](https://github.com/johnpapa/angular-styleguide#style-y010)
* Standardized and rigorous use of JSHint, JSCS, JSDoc

**Comment by vaucouleur** [comment]
The edit and delete buttons, as well as the "posted on and posted by" at the bottom of every view-x.client.view.html pages are, arguably, a form of code duplication across generated modules.

Custom directives could help factoring out those pieces of code.

- On the Pros side, it would be pushing forward the "angular way" (directives), and help people get a concrete example of one or two simple custom directives.

- On the Cons side, it would make sites with a single "business object" module (Article), more complicated than necessary.

**Comment by ilanbiala** [comment]
@lirantal definitely a good idea to have many more directives implemented. Biggest thing is we should move to Angular 1.4 first.

**Comment by trainerbill** [comment]
I created a pagination directive to do paginiation + search easily like in the admin module:

https://github.com/trainerbill/mean/tree/PaginationDirective

We could use it across the entire app.

**Comment by simison** [comment]
Should this be divided into 0.4.x and 0.5.0 stuff (just subtitles, I don't mean having two separate issues) so that we'll have a better picture of the roadmap?

There's a number of PL's that might not be breaking and they could thus be pre-0.5.0.

**Comment by lirantal** [comment]
sure, I updated.

**Comment by roshangade** [comment]
+1 - really great features! Gulp, Angular 1.4, John Papa's Angular Styleguide

**Comment by kokokenada** [comment]
Support for Cordova (and/or Ionic) clients?  This has been the driving reason (for me) on #389 and configurable REST endpoints. 

In the modules I'm developing with MEAN, I use the existing "modules/<module>/client" directory for client code intended for any client, "modules/<module>/client-ionic" for client code intended for ionic only (A watcher automatically updates the ionic app directory). I use "modules/<module>/client-md" for client code intended for angular material ("modules/<module>/client-bts" could house bootstrap specific client code).  The client specific code are the views, CSS, route configurations, some presentation specific controllers (e.g. to deal with $ionicModal or $mdDialog).  

Lots of controller, directive and service Javascript code works perfectly in both client environments. A wrapper deals with toast, alert, confirm.

**Comment by ilanbiala** [comment]
@lirantal since we had some issues with #559, do you want to try to start a PR for the user refactor? I think that is a good thing to revise, because @sielay had some worthwhile suggestions, but they needed tweaking.

On another note, Gulp has still not reached its 4.0 release, but once it does I'll start rewriting the gulpfile and start making gulp == grunt.

**Comment by lirantal** [comment]
Not sure I have the time to take that on but once I do I'll review this list again

**Comment by trendzetter** [comment]
why would you deprecate grunt? can't we keep it? It's not that it is not maintained

**Comment by lirantal** [comment]
@trendzetter we can't maintain 2 build systems, which is what we are doing now with more focus on grunt and less on gulp but it seems that the tide has changed and gulp is definitely winning.

What is your concern about keeping with grunt over switching to gulp?

**Comment by ilanbiala** [comment]
The generator currently only has Gulp (it's used for development), so it would be best if we could do the same here. Supporting one build system with more effort will result in a better boilerplate.

**Comment by mleanos** [comment]
I don't know if this has been addressed.. 

Can we keep Grunt in the project, and just not do any new development with it? If soneone wants to come along and do some work on it, they could submit PR's. However, we don't need to put it as a high priority.

**Comment by ilanbiala** [comment]
I have mixed feelings about that, because it's good that people can just use it if they want, but that means we segment the community and will eventually get a PR that requires us to focus on that at some point, which means we'll never put 0 work into it. Also, it might give users the idea that we support Grunt, when Gulp will pull ahead in terms of features and support and then we'll receive issues on that topic and requests to go back to parity/support Grunt. I'm not sure if there's a perfect way to work out having both systems.

**Comment by mleanos** [comment]
@ilanbiala That makes sense to me, and I think your instincts are spot on. It's probably not work the effort, and we may end up having to support it.

If users really want to use Grunt, they can "re-implement" it, or use previous releases as a guide on adding it.

**Comment by trendzetter** [comment]
@lirantal On closer inspection Gulp seems ok. I was afraid it would be a problem porting over my project and I would have to relearn stuff but it appears the impact is nihil. I was a bit suspicious in the zealous fanaticism that seems to surround gulp. I say, live and let live.

**Comment by marxav** [comment]
@lirantal Have you considered relying only "npm" rather than "gulp" and/or "grunt" as described in https://medium.com/@housecor/why-i-left-gulp-and-grunt-for-npm-scripts-3d6853dd22b8 ?

**Comment by ilanbiala** [comment]
@marxav have you looked into our Gulp setup to see if there's anything we can't do in a node+npm script?

**Comment by codydaig** [comment]
@ilanbiala @mleanos @trainerbill @lirantal @rhutchison @simison and anybody else that I'm forgetting:

I'm going to go through and triage issues and PRs right now. There are a lot of big and awesome PRs on their way and I want to prioritize them. Let's discuss what everyone things is a priority and why. Include specific PRs and issues as well. We'll evaluate and come up with a go forward plan for getting 0.5 finished and released.

**Comment by trainerbill** [comment]
@codydaig I want the JWT PR in asap.  

1.  It's Awesome
2.  It touches many files across the whole app, making conflicts likely
3.  It's basically ready.  Just waiting on a test and socketIO
4.  It will grow in size when we merge other PRs with new functionality
5.  It increases coverage.
6.  It's Awesome

**Comment by codydaig** [comment]
I updated the description above with some tasks that need to get accomplished. The biggest 2 are the refactor of core and users to match the new style guide. Anybody want to take on these refactors? These should be done before we get too deep in enhancements and new features.

**Comment by itelo** [comment]
I checked #389, and i didn't understand if MEAN.js has some plan to be mobile platform too. I'd like this feature...

**Comment by codydaig** [comment]
@itelo #1163 is on the list and in progress.

**Comment by freemind-** [comment]
Any plans for Agular 2.0?

**Comment by ilanbiala** [comment]
Not for 0.5.0.

**Comment by ignasg** [comment]
Anything about ECMAScript 6.x support?
http://es6-features.org/

**Comment by lirantal** [comment]
@meanjs/contributors, @simison @hyperreality @luebken @vaucouleur 
I suggest we close down as many more PRs/issues as we can in the next couple of weeks and ship out 0.5.0 - it has major fixes, including security issues that should go in.

* We obviously won't be addressing the JWT and 0.4.0 user refactor from the TODO list above in the scope of this 0.5.0
* We should however deprecate and remove Grunt completely in favor of Gulp.

Any comments?

**Comment by trendzetter** [comment]
So turns out jwt is not the way to go.
I have been away from the keyboard for months because of back pains. Seems the release is taking too long and it is starting to have stagnating effect. I think we shouldn't wait much longer so we can set new targets that can motivate contributors.

**Comment by trendzetter** [comment]
A lot of bugfixing going on still. Getting it right is also important!

**Comment by mleanos** [comment]
@lirantal I've updated the task list in this issue. And as soon #1175 is merged, we just have some minor-ish PR's to wrap up; some bug fixes, and other front-end enhancements.

**Comment by mleanos** [comment]
@meanjs/contributors I think we're ready to release 0.5.0. Is there anything else that we want merged in?

Anyone else have any thoughts/comments on releasing 0.5.0?

**Comment by dalelotts** [comment]
Nice work! I love this project!  Just one thing, please update to the _very latest_ node and bower dependencies for 0.5.0 (i.e. npm-check-updates -u and bower list) - every time I clone I spend an hour updating the dependencies, fixing code, and running the tests.

**Comment by lirantal** [comment]
@mleanos definitely, I'll push it today.
@dalelotts exactly the reason why I am going to create a shrinkwrap file so we don't have to deal with drifting dependencies.

**Comment by dalelotts** [comment]
@lirantal Great, I think. I'm not sure how I feel about that. I would like to see smaller, more frequent releases - in a small, frequent release model (i.e. continuous delivery) shrink wrapping may not be entirely necessary.

**Comment by lirantal** [comment]
0.5.0 released, thanks everyone!
Let's open a new 0.6.0 thread to discuss there the next step for MEAN.JS
