### ISSUE TITLE
0.4.0 Release

### ISSUE THREAD

**Issue by lirantal** [meanjs/mean#669]
This is a list of all PRs and Issues that we want fixed and merged to 0.4.0 branch before we release.

# General Features
- [x] Admin module support #615 #676
- [x] [Nice to Have] add backend support for Article voting #552 (RESOLVED as not part of 0.4.0)
- [x] #501 Handle 404 errors at Express backend and at Angular frontend #566

# Minor Cleanups
- [x] Task Enhancements #666
- [x] Move Logo, Favicon, and Livereload to Config #664 #685
- [x] Set base title from default config. #662
- [x] Added uploads folder under module/users/client/img/profile so that us… #731 (needs a new PR)
- [x] Enable redirection to previous page after login #487
- [x] Make emails unique #439
- [x] removed /#! in user controllers #587 (needs a new PR) #693

# Tests
- [ ] Server Side Test Coverage #569 (needs a new PR)
- [x] Client side test coverage #663

# Documentation
- [x] Overview, Troubleshooting, and Permalinks #652
- [x] Removed the s at 'express routes' in the menu to match the usage of t… #595

**Comment by codydaig** [comment]
#439 takes care of some of the changes from #587

**Comment by lirantal** [comment]
@codydaig are you sure? they look totally unrelated.

**Comment by codydaig** [comment]
If you look on and around this line: @igorauad made some of those changes. But it does not cover all the places that #! needed to be removed that #587 points out. 
https://github.com/meanjs/mean/pull/439/files#diff-6586a849345903e73352845be92306cfL87

**Comment by simison** [comment]
I'd leave ngBestPractices (#636) PL out and do it thoroughly for 0.5.0 (it's related to #490 style guide).

**Comment by igorauad** [comment]
@codydaig, thanks for pointing. @lirantal #587 can be merged first, then I update #439 accordingly.

**Comment by ilanbiala** [comment]
Style should follow in 0.4.1 or even 0.5.0 depending on how big of a change it is, but since it doesn't change functionality we should be able to do it anytime.

**Comment by ilanbiala** [comment]
@lirantal https://github.com/meanjs/mean/blob/0.4.0/modules/chat/tests/client/chat.client.controller.tests.js is a little bit of an issue, no?

**Comment by ravisuhag** [comment]
We should also get rid for either Gulp or Grunt. I would say Grunt as no doubt Gulp is better choice for performance.

**Comment by lirantal** [comment]
@ravisuhag Gulp is maybe an option for 0.5.0, for 0.4.0 we'll stick with grunt.
@ilanbiala @rhutchison who volunteers to add some tests to https://github.com/meanjs/mean/blob/0.4.0/modules/chat/tests/client/chat.client.controller.tests.js ?

**Comment by cdriscol** [comment]
@lirantal, @ilanbiala  - I added those chat tests as part of #728.  That PR also covers the second bullet in __Tests__ above.

**Comment by lirantal** [comment]
Hi everyone,

We'd like to aggressively push 0.4.0 out before it becomes a monster :-)
We appreciate all the great PRs but with more PRs we delay time because we are all opinionated people (and good that we are), and we're all quite busy and PRs need to be reviewed extensively.

@ilanbiala suggested closing 0.4.0 out by Thursday (tomorrow) so we can do all the release logistics (merging, etc) and this means we need to close only 'core' 0.4.0 and only important PRs for 0.4.0. The remaining 'nice to have' enhancements we will mark as 0.4.x so we can review and possibly merge them as 0.4.1 and so on soon after 0.4.0 is released.

@ilanbiala @codydaig @simison @rhutchison @igorauad @trainerbill @mleanos @cdriscol

**Comment by codydaig** [comment]
@lirantal @ilanbiala Sounds good to me!

**Comment by simison** [comment]
:+1: absolutely.

**Comment by ilanbiala** [comment]
@lirantal just waiting for server side tests if we want to include that in 0.4.0 instead of releasing incrementally in 0.4.x.

**Comment by lirantal** [comment]
since it's a change to the core server.js and grunt I want to push that in a couple of hours for your review.

**Comment by mleanos** [comment]
+1 Sounds great.

**Comment by taninme** [comment]
any update on release date ? thanks :)

**Comment by lirantal** [comment]
@taninme tomorrow/upcoming week.

**Comment by taninme** [comment]
:+1:

**Comment by lirantal** [comment]
before we go ahead with the final 0.4.0 release, if you want to raise a PR for discussion which must be included in 0.4.0 **now is the time**.

**Comment by lirantal** [comment]
@ilanbiala looks like I'm not going to make it for the refactoring of the core server.js as I hoped so if we might want to continue without it if I won't ping anything different in the morning.

**Comment by ilanbiala** [comment]
Ok. If that's the case, we'll release tomorrow morning and we can start taking care of 0.4.1.

**Comment by lirantal** [comment]
Cool, I took the day off tomorrow so we can do it on gitter, I'll probably have my coffee ready by 8:30am (GMT+3)

**Comment by codydaig** [comment]
So that's 10:30 PST?

**Comment by lirantal** [comment]
09:30PM

**Comment by codydaig** [comment]
Whoops. Off by 1 hour.

**Comment by cdriscol** [comment]
:+1: - awesome!

**Comment by taninme** [comment]
released ? missed the party ?

**Comment by lirantal** [comment]
not yet, 2 more PRs to close, mine and @rhutchison and we're done

**Comment by ravitejawedelez** [comment]
any way to know the schedule for release? 
waiting for the admin dashboard..

**Comment by lirantal** [comment]
0.4.0 released now and merged into master branch.
You can also find the 0.4.0 tag here: https://github.com/meanjs/mean/releases/tag/v0.4.0

**Comment by lirantal** [comment]
Thanks everyone for your hard work, couldn't do it with you!

**Comment by igorauad** [comment]
Congrats everyone! Very good work.

**Comment by mleanos** [comment]
:+1: Everyone here is awesome! Didn't have any merge conflicts from 0.4.0 to master :) Thanks @codydaig for prepping that.

**Comment by rbecheras** [comment]
Great! congratulations guys ! :clap:

**Comment by vaucouleur** [comment]
Congrats. Thanks for the excellent work !

**Comment by quanganh206** [comment]
Thansk and Congrats !

**Comment by taninme** [comment]
Congrats all and quick question ..did you add the admin dashboard to 0.4 ?

**Comment by lirantal** [comment]
@taninme yes, it's there.

**Comment by simison** [comment]
Excellent! Nice to come back down from the mountains and there's a new release waiting. Thanks everyone who worked on this. It's a massive pile of great commits!

**Comment by lirantal** [comment]
@simison I'm not going to greet you welcome back until I see some PRs from you :-)
j/k, nice to have you around again!

**Comment by lirantal** [comment]
closing this issue since we already released 0.4.0, you're welcome to continue commenting on any 0.4.0 matters though.
