### ISSUE TITLE
Documentation ToDo

### ISSUE THREAD

**Issue by codydaig** [meanjs/mean#743]
Since 0.4.0 is being released very soon, we need to get the documentation on the website up to date for the 0.4.0 branch. If your interested in helping, comment below with which section you would like to tackle! Thanks :-D

Here's a general list of items in the 0.3.x documentation that need to get brought over and modified:
- [ ] Folder Structure 
- [ ] Configuration 
- [ ] Autoloaded Files
- [ ] NPM 
- [ ] Bower
- [ ] Grunt
- [ ] Express & Routing 
- [x] Passport @codydaig
- [ ] Backend Views
- [x] Server Tests @codydaig
- [ ] AngularJS Tests 
- [ ] AngularJS Modules 
- [x] AngularJS Menus Service @cdriscol 
- [ ] The Article Example

Things that need to be written (that don't exist in 0.3.x):
- [ ] Gulp @zeldar 
- [ ] The Chat Example

**Comment by mleanos** [comment]
@codydaig Thanks for compiling this list. I would love to help out here. Below is a list of what I'm interesting in working on. If someone would like to work on anything on *my* list before I get to it, by all means, go for it...

Folder Structure
Configuration
The Chat Example

**Comment by lirantal** [comment]
@codydaig bless you for the proactive attitude to get this finished! 
@mleanos thanks for helping in buddy!

I'm a server-side guy so I'll take those that are related, starting with:
* server tests
* express & routing
I'll get those nailed first and then we/others can continue to the rest of the list.

**Comment by codydaig** [comment]
@mleanos @lirantal Thanks for helping out. I've got a big project going on this week before the hiring assessment (to determine if I'm a hirable developer or not) then I'll be cranking some of the documentation out as well.

**Comment by cdriscol** [comment]
@codydaig - I'll work on the AngularJS documentation.

**Comment by codydaig** [comment]
@cdriscol Thanks!

**Comment by vaucouleur** [comment]
@codydaig I will do my best to proofread the new documentation and give feedback

**Comment by codydaig** [comment]
@vaucouleur Sweet! :-D

**Comment by cdriscol** [comment]
@codydaig @mleanos @lirantal @vaucouleur  - how do you guys feel about an AngularJS _sub-menu_ in the 0.4.0 docs?  Would look like the following..

![image](https://cloud.githubusercontent.com/assets/5116860/9101749/db391e9e-3ba7-11e5-850f-74ba1791899d.png)

I think it's cleaner than prefixing 3 menu items with 'AngularJS'.  We could also group some other similar menu items together (i.e. build systems > grunt, gulp).

**Comment by codydaig** [comment]
@cdriscol I'm not opposed

**Comment by mleanos** [comment]
@cdriscol That's a really good idea. Thanks.

**Comment by lirantal** [comment]
yep, no problems

**Comment by vaucouleur** [comment]
@cdriscol  Good idea.

**Comment by zeldar** [comment]
I may be late to the party, but I am willing to write the gulp section.

**Comment by lirantal** [comment]
@zeldar We'd love it.
Can you begin by adding a gulp section and document the current setup we have there?

**Comment by zeldar** [comment]
@lirantal Yes, Happy to do that.  I have it mostly written out, just needs a final edit.  Apologies for taking so long.  I had to read the guidelines and get my workflow inline with that for the request.  I'll send the request today/tonight.

**Comment by codydaig** [comment]
@zeldar No worries! We're looking forward too it.

**Comment by ilanbiala** [comment]
@codydaig can you update the checklist at the top? I think we covered some of these, no?

**Comment by codydaig** [comment]
Would anyone be opposed to leaving the npm and bower sections out in the new documentation?
http://meanjs.org/docs/0.3.x/#npm
http://meanjs.org/docs/0.3.x/#bower

**Comment by mleanos** [comment]
@codydaig I think leaving NPM out is fine. As for Bower, maybe just a mention that we're using it as the front-end package manager? No need to list all the libraries that are included in the project.

**Comment by ilanbiala** [comment]
yep leaving out npm is fine.

**Comment by ilanbiala** [comment]
So we don't have one monster issue, can we create separate issues for each task and then people working on a specific task don't get all the chatter?

**Comment by codydaig** [comment]
I will break these into individual issues. We want to keep the issues in this repo, or move them to the other repo?

**Comment by ilanbiala** [comment]
Probably the other, just to declutter this repo from the documentation-specific stuff.

**Comment by danoz-direct** [comment]
Hi everyone,

Dropping in here to see if I can help with the doc in any way? 

I've been working through the repository files one by one, line by line for a while now (simply to help myself understand how things work) and I feel I'm getting a handle on them. Coincidentally I've been taking copious notes for myself along the way which might be helpful to contribute back up to the doc.

Please let me know what you think and then, if so, what you think would be good to start on...

Sincerely,
Dan

**Comment by codydaig** [comment]
@danoz-direct Your welcome to contribute to the documentation in any way you want. All the documentation lives in the github.com/meanjs/meanjs.github.io repo.

**Comment by danoz-direct** [comment]
@codydaig 

Cool, will begin familiarisation with that repo + using Jekyll. 

I'll follow the checklist here on this page as a starting point.

**Comment by codydaig** [comment]
@danoz-direct The checklist on this page is probably outdated. I honestly didn't realize it was still open until you commented. I'd go through and add things that you think would be beneficial to the documentation and run with it.

**Comment by danoz-direct** [comment]
@codydaig  Fair enough, how about we close this general doco issue then in favour of specific individual tickets as things on the doc progress? Over in that other repo maybe?

**Comment by codydaig** [comment]
@danoz-direct Works for me.
