### ISSUE TITLE
0.4.2 Release

### ISSUE THREAD

**Issue by rhutchison** [meanjs/mean#869]
We are tracking towards the release of 0.4.2.  This thread is to discuss what needs to be finalized before we can cut the release.  If there are any PRs or open issues that should be added to the list, please comment below.

### Bug fixes
 - [x] #1039 Switch to using new MongoDB service in Bluemix

### Extras
 - [x] #881 CHANGELOG.md - @ilanbiala, @codydaig
 - [x] #1042 Start testing against Node 5

**Comment by lirantal** [comment]
Looks like I'm not doing anything for 0.4.2, yay!
But seriously, how do we want to approach 0.4.2 from planning perspective? should we start adding here all the open PRs that we wish to merge to 0.4.2 or rather should we just use Github's milestone option and simply assign to 0.4.2, wouldn't that be easier to track and handle?

We can keep this issue open to track/discuss 0.4.2 release items in general.

**Comment by ilanbiala** [comment]
@lirantal let's track everything in the milestone, and as we approach the end of the milestone based on the progress bar, we'll update the list here and this may act as a changelog of sorts?

**Comment by lirantal** [comment]
Great

**Comment by lirantal** [comment]
Quite a few issues still for v0.4.2 to resolve: https://github.com/meanjs/mean/pulls?q=is%3Aopen+milestone%3A0.4.2+is%3Apr

**Comment by ilanbiala** [comment]
@rhutchison can you update the list? @lirantal I think we can say that this is the cutoff for 0.4.2?

**Comment by lirantal** [comment]
Yep

**Comment by ilanbiala** [comment]
@lirantal @codydaig whenever you close an issue in the future, please add it to this list so we don't have to do it all at once.

**Comment by lirantal** [comment]
what do you mean? to which list should we add it?

**Comment by ilanbiala** [comment]
The list in this issue at the top.

**Comment by lirantal** [comment]
@ilanbiala looks like the Changelog is the only thing holding 0.4.2 back?
Any suggestions what we can do about speeding it up?

**Comment by codydaig** [comment]
@lirantal @ilanbiala Here are the open PRs marked for 0.4.2. However, I'm not opposed to moving those out to the next release. https://github.com/meanjs/mean/pulls?q=is%3Aopen+is%3Apr+milestone%3A0.4.2

Also, is the next release going to be 0.4.3 or 0.5.0? I'm voting for 0.5.0

**Comment by ilanbiala** [comment]
Next release should probably be 0.5.0. I think everything but the Lusca should be taken care of in 0.4.2.

**Comment by lirantal** [comment]
We also have a defect or two to handle IIRC in that queue

**Comment by ilanbiala** [comment]
In which queue?

**Comment by lirantal** [comment]
This queue: https://github.com/meanjs/mean/milestones/0.4.2

**Comment by ilanbiala** [comment]
Gotcha

**Comment by ilanbiala** [comment]
@lirantal @codydaig do we want to add all the issues to the top or do you think that's unnecessary now that we have the changelog?

**Comment by codydaig** [comment]
@ilanbiala Just use the changelog. Ryan started this to start discussion on what should be included in 0.4.2 and I personally think this issue can be closed at this point.

**Comment by codydaig** [comment]
@ilanbiala @lirantal So we're just waiting on final review of the new commit message PR and the domain PR. I'm voting to move the domain PR and get 0.4.2 released this week.

**Comment by lirantal** [comment]
Totally agree, already updated that PR.
We don't have any out-standing issues left anymore so 0.4.2 is good to go when we're ready.

Let's put up a plan for it?
* PR to merge 0.4.2 to `master`
* Create a release/tag in Github for 0.4.2 after we merged to master
* Updated Changelog file
* Update generator? package.json? anything else?

What else?

**Comment by ilanbiala** [comment]
@lirantal 0.4.2 is master, so we just create a tag on master.

**Comment by lirantal** [comment]
Right @ilanbiala !

**Comment by lirantal** [comment]
@codydaig @ilanbiala I created a tag for 0.4.2
Hoping we covered everything in the PRs so I am closing this issue and we can continue with the next release.

0.5.0 I assume?

**Comment by mleanos** [comment]
@lirantal Thank you! I'm pretty sure it was decided to jump to 0.5.0 next.

Quite a few big things on the plate for 0.5.0. Should be a fun one :)
